FROM docker:29.2.1-cli@sha256:cab69e2d0a1a2ea9a1ce1060252f439e83483ae41ec09317aecb33b08a0656a5
ARG TARGETARCH
COPY bin/manager-linux-${TARGETARCH} /usr/local/bin/manager
WORKDIR /app
EXPOSE 8080
HEALTHCHECK --interval=30s --timeout=5s --start-period=10s CMD ["manager","healthcheck"]
ENTRYPOINT ["manager"]
