import '@material/web/all.js';
import { Terminal } from '@xterm/xterm';
import { FitAddon } from '@xterm/addon-fit';
import '@xterm/xterm/css/xterm.css';
import './style.css';

type Host = { id:string; name:string; address:string; port:number; user:string; credentialId?:string; hostKey?:string; group?:string; tags?:string[] };
type Page = 'overview'|'hosts'|'containers'|'compose'|'images'|'volumes'|'networks'|'files'|'tunnels'|'commands'|'schedules'|'settings';
type L10n = 'en'|'zh'|'both';
const pages: {id:Page; en:string; zh:string; icon:string}[] = [
  ['overview','Overview','總覽','dashboard'],['hosts','Hosts','主機','dns'],['containers','Containers','容器','deployed_code'],['compose','Compose','編排','account_tree'],['images','Images','映像','image'],['volumes','Volumes','儲存卷','storage'],['networks','Networks','網絡','hub'],['files','Files','檔案','folder'],['tunnels','Tunnels','隧道','route'],['commands','Commands','指令','terminal'],['schedules','Schedules','排程','schedule'],['settings','Settings','設定','settings']
].map(([id,en,zh,icon]) => ({id:id as Page,en,zh,icon}));
const store = <T>(key:string, fallback:T) => ({get:()=>JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback)) as T,set:(v:T)=>localStorage.setItem(key,JSON.stringify(v))});
const pref=store('csm.preferences',{language:'en' as L10n, theme:'system', emoji:true, funnyEn:5, funnyZh:5, narrator:false});
let state={page:'overview' as Page,hosts:[] as Host[],selected:'',openTabs:['overview'] as Page[],drawer:false,settings:pref.get(),version:'Unavailable',updatedAt:'Unavailable'};
const api=async<T>(path:string, init?:RequestInit):Promise<T>=>{const r=await fetch(path,{credentials:'same-origin',headers:{'Content-Type':'application/json',...(init?.headers||{})},...init});if(!r.ok)throw new Error((await r.json().catch(()=>({error:r.statusText}))).error);return r.status===204?undefined as T:await r.json() as T};
const esc=(x:string)=>x.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]!));
const label=(p:{en:string;zh:string})=>state.settings.language==='zh'?p.zh:state.settings.language==='both'?`${p.en} / ${p.zh}`:p.en;
const pageTitle=(id:Page)=>label(pages.find(x=>x.id===id)!);
const host=()=>state.hosts.find(h=>h.id===state.selected);
function notice(message:string){const n=document.querySelector('md-snackbar') as any;n.labelText=message;n.open=true; if(state.settings.narrator) speechSynthesis.speak(new SpeechSynthesisUtterance(message));}
function render(){document.documentElement.dataset.theme=state.settings.theme; const current=host(); document.querySelector('#app')!.innerHTML=`
<div class="shell">
  <header class="topbar"><md-icon-button id="menu" aria-label="Toggle navigation"><md-icon>menu</md-icon></md-icon-button><div class="brand"><md-icon>terminal</md-icon><span>Container SSH Manager</span></div><div class="top-actions"><md-icon-button id="palette" aria-label="Open command palette" title="Ctrl+Shift+F"><md-icon>search</md-icon></md-icon-button><md-icon-button id="theme" aria-label="Change theme"><md-icon>contrast</md-icon></md-icon-button><span class="version">v${esc(state.version)} · ${esc(state.updatedAt)}</span><md-icon-button id="logout" aria-label="Log out"><md-icon>logout</md-icon></md-icon-button></div></header>
  <aside class="nav ${state.drawer?'shown':''}" aria-label="Primary navigation"><div class="host-head"><span>Hosts</span><md-icon-button id="add-host" aria-label="Add host"><md-icon>add</md-icon></md-icon-button></div><div class="host-list">${state.hosts.length?state.hosts.map(h=>`<button class="host ${h.id===state.selected?'selected':''}" data-host="${esc(h.id)}"><md-icon>dns</md-icon><span>${esc(h.name)}</span><small>${esc(h.address)}</small></button>`).join(''):`<p class="empty-small">No hosts yet</p>`}</div><md-divider></md-divider><nav>${pages.map(p=>`<button class="nav-item ${state.page===p.id?'active':''}" data-page="${p.id}"><md-icon>${p.icon}</md-icon><span>${esc(label(p))}</span></button>`).join('')}</nav></aside>
  <main><div class="tabs" role="tablist">${state.openTabs.map(t=>`<button class="tab ${t===state.page?'active':''}" data-page="${t}" role="tab">${esc(pageTitle(t))}${t!=='overview'?'<md-icon class="close" aria-hidden="true">close</md-icon>':''}</button>`).join('')}</div><section class="content">${pageContent(current)}</section></main>
  <aside class="jobs" aria-label="Job activity"><div><h2>Jobs</h2><md-icon-button id="close-jobs" aria-label="Close jobs"><md-icon>close</md-icon></md-icon-button></div><p class="muted">No active jobs. Operations will appear here with their real status.</p></aside><button class="job-toggle" id="jobs" aria-label="Open job activity">Jobs <md-icon>monitoring</md-icon></button>
</div><md-dialog id="dialog"><div slot="headline" id="dialog-title"></div><form slot="content" id="dialog-content"></form><div slot="actions"><md-text-button form="dialog-content" value="cancel">Cancel</md-text-button><md-filled-button form="dialog-content" value="confirm">Continue</md-filled-button></div></md-dialog><md-snackbar></md-snackbar>`;
 bind(); }
function noHost(action:string){return `<div class="empty"><md-icon>dns</md-icon><h1>No host selected</h1><p>Add a host or select one in the sidebar before ${action}.</p><md-filled-button id="empty-add"><md-icon slot="icon">add</md-icon>Add host</md-filled-button></div>`}
function pageContent(h?:Host){const selected=h?`<span class="target"><md-icon>dns</md-icon>${esc(h.name)} · ${esc(h.user)}@${esc(h.address)}</span>`:''; if(state.page==='overview')return `<div class="page-title"><div><h1>Overview</h1><p>Manage container services over SSH without guessing the target.</p></div>${selected}</div>${state.hosts.length?`<div class="cards"><article><md-icon>dns</md-icon><strong>${state.hosts.length}</strong><span>Configured hosts</span></article><article><md-icon>inventory_2</md-icon><strong>—</strong><span>Containers load after a host is selected</span></article><article><md-icon>pending_actions</md-icon><strong>0</strong><span>Active jobs</span></article></div><section class="surface"><h2>Start here</h2><p>Select a host to open its containers, files, terminal, and other live controls.</p></section>`:noHost('managing services')}`;
 if(state.page==='hosts')return `<div class="page-title"><div><h1>Hosts</h1><p>SSH connections are stored locally. Secret values are never displayed again.</p></div><md-filled-button id="create-host"><md-icon slot="icon">add</md-icon>Add host</md-filled-button></div>${state.hosts.length?`<div class="host-grid">${state.hosts.map(x=>`<article class="surface"><h2>${esc(x.name)}</h2><p>${esc(x.user)}@${esc(x.address)}:${x.port}</p><p class="muted">${x.hostKey?'Host key pinned':'Host key not enrolled'}</p><div class="actions"><md-outlined-button data-select="${esc(x.id)}">Open</md-outlined-button><md-text-button data-delete="${esc(x.id)}">Remove</md-text-button></div></article>`).join('')}</div>`:noHost('adding a connection')}`;
 if(!h)return noHost(`using ${pageTitle(state.page).toLowerCase()}`);
 if(state.page==='commands')return `<div class="page-title"><div><h1>Commands</h1><p>Command output is not retained. Confirm the target before execution.</p></div>${selected}</div><div class="split"><section class="surface"><h2>Run a command</h2><md-outlined-text-field id="command" label="Command" type="textarea" rows="5" required></md-outlined-text-field><md-filled-button id="run-command"><md-icon slot="icon">play_arrow</md-icon>Run on ${esc(h.name)}</md-filled-button><p class="muted" id="command-result"></p></section><section class="surface"><h2>Interactive terminal</h2><div id="terminal" aria-label="SSH terminal"></div><p class="muted">Terminal opens only when requested and connects to the selected host.</p><md-outlined-button id="connect-terminal">Connect terminal</md-outlined-button></section></div>`;
 if(state.page==='files')return `<div class="page-title"><div><h1>Files</h1><p>Edit text safely using conflict detection.</p></div>${selected}</div><section class="surface"><div class="actions"><md-outlined-text-field id="file-path" label="Remote path" value="/"></md-outlined-text-field><md-filled-button id="list-files">Browse</md-filled-button></div><div id="file-results" class="empty-small">Choose Browse to request the current directory from ${esc(h.name)}.</div></section>`;
 if(state.page==='tunnels')return `<div class="page-title"><div><h1>Tunnels</h1><p>Local listeners bind to loopback only.</p></div>${selected}</div><section class="surface"><h2>Create tunnel</h2><div class="form-grid"><md-outlined-select id="direction" label="Direction"><md-select-option value="local">Local</md-select-option><md-select-option value="reverse">Reverse</md-select-option></md-outlined-select><md-outlined-text-field id="listen-address" label="Listen address" value="127.0.0.1"></md-outlined-text-field><md-outlined-text-field id="listen-port" label="Listen port" type="number"></md-outlined-text-field><md-outlined-text-field id="target-address" label="Target address"></md-outlined-text-field><md-outlined-text-field id="target-port" label="Target port" type="number"></md-outlined-text-field></div><md-filled-button id="create-tunnel">Create tunnel for ${esc(h.name)}</md-filled-button></section>`;
 if(state.page==='schedules')return `<div class="page-title"><div><h1>Schedules</h1><p>Scheduled jobs are auto-approved by default. Review the target and command before saving.</p></div>${selected}</div><section class="surface"><h2>No schedules yet</h2><p>Create a schedule after defining a saved command. One schedule runs at a time per host.</p><md-filled-button id="new-schedule">New schedule</md-filled-button></section>`;
 if(state.page==='settings')return settingsContent();
 return `<div class="page-title"><div><h1>${esc(pageTitle(state.page))}</h1><p>Live data appears after the service endpoint is available.</p></div>${selected}</div><section class="empty"><md-icon>hourglass_empty</md-icon><h2>No data loaded</h2><p>This view has no placeholder records. Select a host and refresh when the server endpoint is available.</p><md-outlined-button id="refresh">Refresh</md-outlined-button></section>`; }
function settingsContent(){const s=state.settings;return `<div class="page-title"><div><h1>Settings</h1><p>Preferences are stored in this browser.</p></div></div><div class="settings"><section class="surface"><h2>Language and presentation</h2><md-outlined-select id="language" label="Language" value="${s.language}"><md-select-option value="en">English</md-select-option><md-select-option value="zh">繁體中文</md-select-option><md-select-option value="both">Bilingual</md-select-option></md-outlined-select><md-outlined-select id="theme-setting" label="Theme" value="${s.theme}"><md-select-option value="system">System</md-select-option><md-select-option value="light">Light</md-select-option><md-select-option value="dark">Dark</md-select-option></md-outlined-select><md-switch id="emoji" ${s.emoji?'selected':''}>Show emojis in dialogs and messages</md-switch></section><section class="surface"><h2>Voice</h2><label>English playfulness <input id="funny-en" type="range" min="1" max="5" value="${s.funnyEn}"></label><label>Cantonese playfulness <input id="funny-zh" type="range" min="1" max="5" value="${s.funnyZh}"></label><md-switch id="narrator" ${s.narrator?'selected':''}>Narrate important events</md-switch><p class="muted">Playfulness changes tone, never operational facts.</p></section><section class="surface"><h2>Personal vocabulary</h2><p>Load a local JSON file to customize private wording. The file stays in this browser and is never sent to the server.</p><input id="vocabulary" type="file" accept="application/json"><md-text-button id="clear-vocabulary">Clear local vocabulary</md-text-button></section><section class="surface"><h2>Safety</h2><p>Destructive actions always require confirmation. Stored credentials are represented only by metadata.</p><md-outlined-button id="logout-settings">Log out</md-outlined-button></section></div>`;}
function bind(){document.querySelectorAll('[data-page]').forEach(e=>e.addEventListener('click',()=>open((e as HTMLElement).dataset.page as Page)));document.querySelectorAll('[data-host]').forEach(e=>e.addEventListener('click',()=>{state.selected=(e as HTMLElement).dataset.host!;state.drawer=false;render()}));document.querySelectorAll('[data-select]').forEach(e=>e.addEventListener('click',()=>{state.selected=(e as HTMLElement).dataset.select!;open('overview')}));document.querySelectorAll('[data-delete]').forEach(e=>e.addEventListener('click',()=>confirmDelete((e as HTMLElement).dataset.delete!)));
 document.querySelector('#menu')?.addEventListener('click',()=>{state.drawer=!state.drawer;render()});document.querySelector('#add-host')?.addEventListener('click',hostDialog);document.querySelector('#create-host')?.addEventListener('click',hostDialog);document.querySelector('#empty-add')?.addEventListener('click',hostDialog);document.querySelector('#logout')?.addEventListener('click',logout);document.querySelector('#logout-settings')?.addEventListener('click',logout);document.querySelector('#theme')?.addEventListener('click',()=>{state.settings.theme=state.settings.theme==='dark'?'light':'dark';saveSettings();render()});document.querySelector('#palette')?.addEventListener('click',paletteDialog);document.querySelector('#jobs')?.addEventListener('click',()=>document.body.classList.toggle('jobs-open'));document.querySelector('#close-jobs')?.addEventListener('click',()=>document.body.classList.remove('jobs-open'));
 document.querySelector('#run-command')?.addEventListener('click',runCommand);document.querySelector('#connect-terminal')?.addEventListener('click',terminal);document.querySelector('#list-files')?.addEventListener('click',listFiles);document.querySelector('#create-tunnel')?.addEventListener('click',createTunnel);document.querySelector('#refresh')?.addEventListener('click',()=>loadHosts());document.querySelector('#new-schedule')?.addEventListener('click',()=>notice('Schedule editor will become available with the jobs API.'));
 ['language','theme-setting','emoji','narrator','funny-en','funny-zh'].forEach(id=>document.querySelector('#'+id)?.addEventListener('change',()=>{const el=document.querySelector('#'+id) as any;if(id==='language')state.settings.language=el.value;if(id==='theme-setting')state.settings.theme=el.value;if(id==='emoji')state.settings.emoji=el.selected;if(id==='narrator')state.settings.narrator=el.selected;if(id==='funny-en')state.settings.funnyEn=+el.value;if(id==='funny-zh')state.settings.funnyZh=+el.value;saveSettings();render()}));document.querySelector('#vocabulary')?.addEventListener('change',vocabulary);document.querySelector('#clear-vocabulary')?.addEventListener('click',()=>{localStorage.removeItem('csm.vocabulary');notice('Local vocabulary cleared.')});window.onkeydown=e=>{if(e.ctrlKey&&e.shiftKey&&e.key.toLowerCase()==='f'){e.preventDefault();paletteDialog()}};}
function open(p:Page){state.page=p;if(!state.openTabs.includes(p))state.openTabs.push(p);state.drawer=false;render()};function saveSettings(){pref.set(state.settings)}
function dialog(title:string, body:string, handler:()=>void|Promise<void>){const d=document.querySelector('#dialog') as any;(document.querySelector('#dialog-title')!).textContent=title;(document.querySelector('#dialog-content')!).innerHTML=body;d.addEventListener('close',async()=>{if(d.returnValue==='confirm')await handler()},{once:true});d.show();}
function hostDialog(){dialog('Add host',`<div class="dialog-form"><md-outlined-text-field id="h-name" label="Name" required></md-outlined-text-field><md-outlined-text-field id="h-address" label="Address" required></md-outlined-text-field><md-outlined-text-field id="h-port" label="Port" type="number" value="22" required></md-outlined-text-field><md-outlined-text-field id="h-user" label="User" required></md-outlined-text-field><md-outlined-select id="h-kind" label="Credential type"><md-select-option value="password">Password</md-select-option><md-select-option value="privateKey">Private key</md-select-option></md-outlined-select><md-outlined-text-field id="h-secret" label="Credential secret" type="password" required supporting-text="Stored secret is never shown again."></md-outlined-text-field></div>`,async()=>{const get=(id:string)=>(document.querySelector('#'+id) as any).value.trim();try{const credential=await api<any>('/api/v1/credentials',{method:'POST',body:JSON.stringify({name:get('h-name')+' credential',kind:get('h-kind'),secret:get('h-secret')})});const created=await api<Host>('/api/v1/hosts',{method:'POST',body:JSON.stringify({name:get('h-name'),address:get('h-address'),port:+get('h-port'),user:get('h-user'),credentialId:credential.id,jumpIds:[],tags:[]})});state.hosts.push(created);state.selected=created.id;notice('Host added. Test and enroll its host key before sensitive work.');open('hosts')}catch(e){notice((e as Error).message)}})}
function confirmDelete(id:string){const h=state.hosts.find(x=>x.id===id);dialog('Remove host',`<p>Remove <strong>${esc(h?.name||'this host')}</strong>? This removes only its connection record. Type the host name to confirm.</p><md-outlined-text-field id="confirm-name" label="Host name"></md-outlined-text-field>`,async()=>{if((document.querySelector('#confirm-name') as any).value!==h?.name)return notice('Host name did not match.');try{await api('/api/v1/hosts/'+id,{method:'DELETE'});state.hosts=state.hosts.filter(x=>x.id!==id);if(state.selected===id)state.selected='';notice('Host removed.');render()}catch(e){notice((e as Error).message)}})}
async function runCommand(){const cmd=(document.querySelector('#command') as any).value.trim();if(!cmd)return notice('Enter a command first.');try{const r=await api<{exitCode:number}>(`/api/v1/hosts/${state.selected}/run`,{method:'POST',body:JSON.stringify({command:cmd})});(document.querySelector('#command-result')!).textContent=`Command completed with exit code ${r.exitCode}. Output was not stored.`}catch(e){notice((e as Error).message)}}
async function listFiles(){const path=(document.querySelector('#file-path') as any).value||'/';try{const items=await api<any[]>(`/api/v1/hosts/${state.selected}/files?path=${encodeURIComponent(path)}`);(document.querySelector('#file-results')!).innerHTML=items.length?`<ul class="file-list">${items.map(x=>`<li><md-icon>${x.directory?'folder':'description'}</md-icon>${esc(x.name||x.path)}</li>`).join('')}</ul>`:'<p>No entries found.</p>'}catch(e){notice((e as Error).message)}}
async function createTunnel(){const g=(id:string)=>(document.querySelector('#'+id) as any).value;try{await api('/api/v1/tunnels',{method:'POST',body:JSON.stringify({hostId:state.selected,direction:g('direction'),listenAddress:g('listen-address'),listenPort:+g('listen-port'),targetAddress:g('target-address'),targetPort:+g('target-port')})});notice('Tunnel created. Its lifecycle appears when the service reports it.')}catch(e){notice((e as Error).message)}}
function terminal(){const el=document.querySelector('#terminal') as HTMLElement;el.innerHTML='';const t=new Terminal({theme:{background:'#10131d'}});const fit=new FitAddon();t.loadAddon(fit);t.open(el);fit.fit();const ws=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/api/v1/hosts/${state.selected}/terminal`);ws.onopen=()=>{fit.fit();ws.send(JSON.stringify({type:'resize',cols:t.cols,rows:t.rows}));t.write('Connected.\r\n')};ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.type==='output')t.write(m.data);if(m.type==='status')t.write(`\r\n[${m.state}] ${m.message}\r\n`)};ws.onerror=()=>t.write('\r\nConnection error.\r\n');t.onData((data:string)=>ws.readyState===WebSocket.OPEN&&ws.send(JSON.stringify({type:'input',data})));}
function paletteDialog(){dialog('Command palette',`<md-outlined-text-field id="palette-search" label="Search pages and settings" autofocus></md-outlined-text-field><div id="palette-results" class="palette-results">${pages.map(p=>`<button data-palette="${p.id}"><md-icon>${p.icon}</md-icon>${esc(pageTitle(p.id))}</button>`).join('')}</div>`,()=>{});setTimeout(()=>{const f=document.querySelector('#palette-search') as HTMLInputElement;f?.focus();f?.addEventListener('input',()=>document.querySelectorAll('[data-palette]').forEach(x=>(x as HTMLElement).hidden=!(x.textContent||'').toLowerCase().includes(f.value.toLowerCase())));document.querySelectorAll('[data-palette]').forEach(x=>x.addEventListener('click',()=>{(document.querySelector('#dialog') as any).close('cancel');open((x as HTMLElement).dataset.palette as Page)}))})}
async function vocabulary(e:Event){const f=(e.target as HTMLInputElement).files?.[0];if(!f)return;if(f.size>262144)return notice('Vocabulary file is too large.');try{const value=JSON.parse(await f.text());if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('Invalid vocabulary JSON.');localStorage.setItem('csm.vocabulary',JSON.stringify(value));notice('Local vocabulary loaded.')}catch{notice('Vocabulary file was not accepted.')}}
async function logout(){try{await api('/api/v1/logout',{method:'POST'});location.reload()}catch(e){notice((e as Error).message)}}
async function loadHosts(){try{state.hosts=await api<Host[]>('/api/v1/hosts');if(!state.selected&&state.hosts[0])state.selected=state.hosts[0].id}catch(e){notice((e as Error).message)}render()}
async function init(){try{const session=await api<{authenticated:boolean}>('/api/v1/session');if(!session.authenticated){location.href='/login';return}}catch{location.href='/login';return}try{const m=await api<{version:string;updatedAt:string}>('/api/v1/version');state.version=m.version;state.updatedAt=new Date(m.updatedAt).toLocaleString()}catch{}await loadHosts()};init();
